//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puesto
    {
        public int id { get; set; }
        public string Compañia { get; set; }
        public string posicion { get; set; }
        public string ubicacion { get; set; }
        public string descripcion { get; set; }
        public string aplicar { get; set; }
        public string publico { get; set; }
        public string Email { get; set; }
        public string Categoria { get; set; }
        public string Tipo { get; set; }
    }
}
